"""initial schema

Revision ID: e5c7bce239f0
Revises: 
Create Date: 2026-07-09 12:53:53.589694+00:00
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e5c7bce239f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('user', 'finance', 'admin', name='user_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_id_created_at', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_table('export_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('xlsx', 'csv', 'json', 'zip', name='export_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='export_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_export_tasks_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_tasks'))
    )
    op.create_index('ix_export_tasks_created_by_created_at', 'export_tasks', ['created_by', 'created_at'], unique=False)
    op.create_table('invoice_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('file_ext', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('base64_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'ocr_queued', 'ocr_running', 'ocr_done', 'ocr_failed', 'deleted', name='document_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_invoice_documents_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_documents'))
    )
    op.create_index('ix_invoice_documents_sha256', 'invoice_documents', ['sha256'], unique=False)
    op.create_index('ix_invoice_documents_status_created_at', 'invoice_documents', ['status', 'created_at'], unique=False)
    op.create_index('ix_invoice_documents_uploaded_by_created_at', 'invoice_documents', ['uploaded_by', 'created_at'], unique=False)
    op.create_table('ocr_provider_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('credential_ciphertext', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credential_fingerprint', sa.String(length=120), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('api_version', sa.String(length=40), nullable=False),
    sa.Column('qps_limit', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('quota_source', sa.Enum('manual', 'provider_api', 'estimated', name='quota_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('free_quota_total', sa.Integer(), nullable=True),
    sa.Column('free_quota_used', sa.Integer(), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_warning_percent', sa.Integer(), nullable=False),
    sa.Column('quota_warning_remaining', sa.Integer(), nullable=False),
    sa.Column('last_test_status', sa.String(length=40), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ocr_provider_configs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_ocr_provider_configs_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_provider_configs'))
    )
    op.create_index('ix_ocr_provider_configs_provider_enabled', 'ocr_provider_configs', ['provider', 'enabled'], unique=False)
    op.create_index('ix_ocr_provider_configs_single_default', 'ocr_provider_configs', ['is_default'], unique=True, postgresql_where=sa.text('enabled AND is_default'))
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('latest_ocr_job_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_type', sa.String(length=120), nullable=True),
    sa.Column('invoice_code', sa.String(length=80), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('seller_tax_id', sa.String(length=80), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_tax_id', sa.String(length=80), nullable=True),
    sa.Column('amount_without_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_with_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('check_code', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expense_scene', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'recognizing', 'needs_review', 'confirmed', 'failed', 'duplicate_suspected', 'archived', 'deleted', name='invoice_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_duplicate_suspected', sa.Boolean(), nullable=False),
    sa.Column('raw_ocr_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_invoices_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_documents.id'], name=op.f('fk_invoices_document_id_invoice_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index('ix_invoices_amount_with_tax', 'invoices', ['amount_with_tax'], unique=False)
    op.create_index('ix_invoices_buyer_name', 'invoices', ['buyer_name'], unique=False)
    op.create_index('ix_invoices_code_number_date', 'invoices', ['invoice_code', 'invoice_number', 'invoice_date'], unique=False)
    op.create_index('ix_invoices_invoice_date', 'invoices', ['invoice_date'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('ix_invoices_seller_name', 'invoices', ['seller_name'], unique=False)
    op.create_index('ix_invoices_status_created_at', 'invoices', ['status', 'created_at'], unique=False)
    op.create_table('ocr_provider_usage_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_config_id', sa.Uuid(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('successful_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('estimated_billable_calls', sa.Integer(), nullable=False),
    sa.Column('provider_reported_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_config_id'], ['ocr_provider_configs.id'], name=op.f('fk_ocr_provider_usage_daily_provider_config_id_ocr_provider_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_provider_usage_daily')),
    sa.UniqueConstraint('provider_config_id', 'usage_date', 'action', name='uq_ocr_provider_usage_daily_provider_date_action')
    )
    op.create_table('ocr_quota_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_config_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Enum('info', 'warning', 'critical', name='quota_alert_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'acknowledged', 'resolved', name='quota_alert_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('quota_total', sa.Integer(), nullable=True),
    sa.Column('quota_used', sa.Integer(), nullable=True),
    sa.Column('quota_remaining', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_ocr_quota_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_config_id'], ['ocr_provider_configs.id'], name=op.f('fk_ocr_quota_alerts_provider_config_id_ocr_provider_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_quota_alerts'))
    )
    op.create_index('ix_ocr_quota_alerts_status_level', 'ocr_quota_alerts', ['status', 'level'], unique=False)
    op.create_table('duplicate_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('matched_invoice_id', sa.Uuid(), nullable=False),
    sa.Column('rule', sa.String(length=120), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed_duplicate', 'ignored', name='duplicate_check_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_duplicate_checks_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['invoices.id'], name=op.f('fk_duplicate_checks_matched_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_checks'))
    )
    op.create_index('ix_duplicate_checks_invoice_status', 'duplicate_checks', ['invoice_id', 'status'], unique=False)
    op.create_table('invoice_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('ocr_value', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_invoice_corrections_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_corrections_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_corrections'))
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('raw_item_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_table('ocr_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('provider_config_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'succeeded', 'failed_retryable', 'retry_scheduled', 'failed_final', 'normalizing', 'completed', 'canceled', name='ocr_job_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('provider_error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('raw_request_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_documents.id'], name=op.f('fk_ocr_jobs_document_id_invoice_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_ocr_jobs_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_config_id'], ['ocr_provider_configs.id'], name=op.f('fk_ocr_jobs_provider_config_id_ocr_provider_configs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_jobs')),
    sa.UniqueConstraint('idempotency_key', name='uq_ocr_jobs_idempotency_key')
    )
    op.create_index('ix_ocr_jobs_document_id_created_at', 'ocr_jobs', ['document_id', 'created_at'], unique=False)
    op.create_index('ix_ocr_jobs_status_created_at', 'ocr_jobs', ['status', 'created_at'], unique=False)
    op.create_foreign_key('fk_invoices_latest_ocr_job_id_ocr_jobs', 'invoices', 'ocr_jobs', ['latest_ocr_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoices_latest_ocr_job_id_ocr_jobs', 'invoices', type_='foreignkey')
    op.drop_index('ix_ocr_jobs_status_created_at', table_name='ocr_jobs')
    op.drop_index('ix_ocr_jobs_document_id_created_at', table_name='ocr_jobs')
    op.drop_table('ocr_jobs')
    op.drop_table('invoice_items')
    op.drop_table('invoice_corrections')
    op.drop_index('ix_duplicate_checks_invoice_status', table_name='duplicate_checks')
    op.drop_table('duplicate_checks')
    op.drop_index('ix_ocr_quota_alerts_status_level', table_name='ocr_quota_alerts')
    op.drop_table('ocr_quota_alerts')
    op.drop_table('ocr_provider_usage_daily')
    op.drop_index('ix_invoices_status_created_at', table_name='invoices')
    op.drop_index('ix_invoices_seller_name', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_invoice_date', table_name='invoices')
    op.drop_index('ix_invoices_code_number_date', table_name='invoices')
    op.drop_index('ix_invoices_buyer_name', table_name='invoices')
    op.drop_index('ix_invoices_amount_with_tax', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_ocr_provider_configs_single_default', table_name='ocr_provider_configs', postgresql_where=sa.text('enabled AND is_default'))
    op.drop_index('ix_ocr_provider_configs_provider_enabled', table_name='ocr_provider_configs')
    op.drop_table('ocr_provider_configs')
    op.drop_index('ix_invoice_documents_uploaded_by_created_at', table_name='invoice_documents')
    op.drop_index('ix_invoice_documents_status_created_at', table_name='invoice_documents')
    op.drop_index('ix_invoice_documents_sha256', table_name='invoice_documents')
    op.drop_table('invoice_documents')
    op.drop_index('ix_export_tasks_created_by_created_at', table_name='export_tasks')
    op.drop_table('export_tasks')
    op.drop_index('ix_audit_logs_actor_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
